# Generated by Django 5.1 on 2026-05-02 19:06

import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_expiringtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=login.models.user_profile_image_path),
        ),
    ]
