# Generated by Django 5.1 on 2026-05-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre.'}, help_text='Requerido. Puede incluir letras, numeros, espacios y simbolos comunes.', max_length=150, unique=True),
        ),
    ]
