# Generated by Codex on 2026-04-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import testimonios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(max_length=800)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    'profile_image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=testimonios.models.testimonial_image_path,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pendiente'),
                            ('PUBLISHED', 'Publicado'),
                            ('REJECTED', 'Rechazado'),
                        ],
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                ('moderation_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='testimonials',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
