# Generated by Django 5.1 on 2026-05-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='profile_image',
        ),
    ]
