from rest_framework import serializers
from .models import BraceletType, Bracelet, PurchaseReceipt


class BraceletTypeSerializer(serializers.ModelSerializer):
    """
    Serializer for the bracelet types catalog.
    Includes all fields, including the ImageField (image).
    """
    class Meta:
        model = BraceletType
        fields = '__all__'
        # Returns: id, name, price, attraction_uses, food_balance,
        # description, image, etc.


class BraceletSerializer(serializers.ModelSerializer):
    """
    Serializer for an individual bracelet, referencing a BraceletType.
    """
    # Show the full BraceletType info in read-only mode
    bracelet_type = BraceletTypeSerializer(read_only=True)

    # Allow creating/updating via the ID of the BraceletType
    bracelet_type_id = serializers.PrimaryKeyRelatedField(
        queryset=BraceletType.objects.all(),
        source='bracelet_type',
        write_only=True
    )

    class Meta:
        model = Bracelet
        # Example: We include the fields you need
        fields = [
            'id',
            'bracelet_type',  # read
            'bracelet_type_id',  # write
            'bracelet_code',   # read (auto-generated by signals)
            'current_balance',
        ]
        # 'bracelet_type' will be a nested object when reading,
        # 'bracelet_type_id' is used for POST/PUT.


class PurchaseReceiptSerializer(serializers.ModelSerializer):
    bracelet = BraceletSerializer(read_only=True)
    user_name = serializers.ReadOnlyField(source='user.username')

    class Meta:
        model = PurchaseReceipt
        fields = [
            'id',
            'user',
            'user_name',
            'bracelet',
            'purchase_date',
            'purchase_code',
        ]
        read_only_fields = [
            'user',
            'bracelet',
            'purchase_date',
            'purchase_code',
        ]
