# Generated by Django 5.1 on 2025-01-17 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BraceletType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('attraction_uses', models.PositiveIntegerField(default=0)),
                ('food_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bracelets/')),
            ],
        ),
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bracelet_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bracelet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracelets', to='compra_brazaletes.bracelettype')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_receipts', to='compra_brazaletes.bracelet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
