# Generated by Django 5.1 on 2025-01-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_brazaletes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='attraction_uses_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
