# Generated by Django 5.1 on 2025-01-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_brazaletes', '0002_bracelet_attraction_uses_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='payment_method',
            field=models.CharField(choices=[('INTERNAL', 'Saldo Interno'), ('PAYPAL', 'PayPal')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
