# Generated by Django 5.1 on 2025-01-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_brazaletes', '0003_purchasereceipt_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('CAPTURED', 'Capturado'), ('REFUNDED', 'Reembolsado')], default='CREATED', max_length=20),
        ),
    ]
