# Generated by Django 5.1 on 2026-04-22 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracciones_comidas', '0001_initial'),
        ('compra_brazaletes', '0005_update_purchasereceipt_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BraceletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ATTRACTION_CONSUMPTION', 'Consumo de atraccion'), ('FOOD_CONSUMPTION', 'Consumo de comida')], max_length=40)),
                ('concept', models.CharField(max_length=150)),
                ('balance_delta', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('uses_delta', models.IntegerField(default=0)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('uses_before', models.PositiveIntegerField(default=0)),
                ('uses_after', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelet_transactions', to='atracciones_comidas.attractions')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='compra_brazaletes.bracelet')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelet_transactions', to='atracciones_comidas.food')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelet_transactions', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_bracelet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
