# Generated by Django 5.1 on 2026-04-29 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_brazaletes', '0007_bracelettype_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bracelettransaction',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelet_transactions', to='compra_brazaletes.purchasereceipt'),
        ),
        migrations.AlterField(
            model_name='bracelettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ACTIVATION', 'Activacion de brazalete'), ('ATTRACTION_CONSUMPTION', 'Consumo de atraccion'), ('FOOD_CONSUMPTION', 'Consumo de comida')], max_length=40),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('REFUNDED', 'Reembolsada')], default='PENDING', max_length=20)),
                ('channel', models.CharField(choices=[('INTERNAL_BALANCE', 'Saldo interno'), ('PAYPAL', 'PayPal')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='compra_brazaletes.purchasereceipt')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='bracelettransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelet_transactions', to='compra_brazaletes.sale'),
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('initial_food_balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('initial_attraction_uses', models.PositiveIntegerField(default=0)),
                ('bracelet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_line', to='compra_brazaletes.bracelet')),
                ('bracelet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='compra_brazaletes.bracelettype')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='compra_brazaletes.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='bracelettransaction',
            name='sale_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelet_transactions', to='compra_brazaletes.saleline'),
        ),
    ]
