# Generated by Django 5.1 on 2026-04-29 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_brazaletes', '0008_bracelet_owner_bracelettransaction_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelettransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bracelettransaction',
            name='reverted_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_transactions', to='compra_brazaletes.bracelettransaction'),
        ),
        migrations.AlterField(
            model_name='bracelettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ACTIVATION', 'Activacion de brazalete'), ('ATTRACTION_CONSUMPTION', 'Consumo de atraccion'), ('FOOD_CONSUMPTION', 'Consumo de comida'), ('ADMIN_ADJUSTMENT', 'Ajuste administrativo'), ('REVERSAL', 'Reverso de movimiento')], max_length=40),
        ),
    ]
